######################################################################
# Automatically generated by qmake (3.0) ?? ?? 15 14:11:22 2016
######################################################################

TEMPLATE = app
TARGET = QtRedis
INCLUDEPATH += .

QT += network

# Input
HEADERS += qReader.h qReadisTest.h qRedis.h
SOURCES += main.cpp qReader.cpp qReadisTest.cpp qRedis.cpp
